version: '3.9'

services:
  pythonapp:
    container_name: flask-docker-awslambda
    image: flask-docker-awslambda:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - PGHOST     = db
      - PGPORT     = 5432
      - PGDATABASE = postgres
      - PGUSER     = postgres
      - PGPASSWORD = postgres
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}